# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_newstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsType',
            field=models.CharField(choices=[('health', '健康'), ('tech', '科学'), ('eat', '饮食')], max_length=10),
        ),
    ]
